affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 5
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 6
symbolic.funs_name.0:
- - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - x
symbolic.funs_name.1:
- - x
  - x
  - x
symbolic_enabled: true
width:
- - 3
  - 0
- - 3
  - 0
- - 1
  - 0
